deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: ballergradients.com
  endpoint: ballergradients.com.s3-website-us-east-1.amazonaws.com
  region: us-east-1
  acl: public_read
  detect_encoding: true
