language: python

python:
  - "3.4"

script:
  - mkdir build
  - cp *.html build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "ballergradients.com"
  region: "us-east-1"
  skip_cleanup: true
  local_dir: build
  detect_encoding: true
